### ISSUE TITLE
File not found error on lanscan scan

### ISSUE THREAD

**Issue by DanBrown47** [sumpfgottheit/lanscan#8]
FileNotFoundError: [Errno 2] No such file or directory: '/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/lanscan/logging.yaml'

I have installed all the pip requirements

Detailed
Traceback (most recent call last):
  File "/home/rook/work/rooksbyte/src/env/bin/lanscan", line 8, in <module>
    sys.exit(main())
  File "/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/lanscan/lanscan.py", line 413, in main
    configure_logger(debug)
  File "/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/lanscan/lanscan.py", line 72, in configure_logger
    with open(filename) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rook/work/rooksbyte/src/env/lib/python3.8/site-packages/lanscan/logging.yaml'

**Comment by DanBrown47** [comment]
Workaround this is to manually copy the file from repo tho the location.
